# Generated by Django 5.0.3 on 2024-03-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_name', models.CharField(max_length=15)),
                ('mobile_model', models.CharField(max_length=15)),
                ('EMEI', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=15)),
            ],
        ),
    ]
