# Generated by Django 5.0.3 on 2024-03-24 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('total_amount', models.FloatField()),
                ('sname', models.CharField(max_length=20)),
                ('productfk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product_model')),
                ('supplierfk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier_model')),
            ],
        ),
    ]
